services:
  grafana:
    container_name: grafana-data-sources
    image: grafana/grafana-enterprise:${GF_VERSION:-latest}
    ports:
      - "3000:3000"
    environment:
      TERM: linux
      GF_DEFAULT_APP_MODE: development
      GF_LOG_LEVEL: debug
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_ENTERPRISE_LICENSE_TEXT: ${GF_ENTERPRISE_LICENSE_TEXT}
      GF_PLUGINS_PREINSTALL: >-
        elasticsearch,
        zipkin
      GF_INSTALL_PLUGINS: >-
        dlopes7-appdynamics-datasource,
        grafana-adobeanalytics-datasource,
        grafana-amazonprometheus-datasource,
        grafana-astradb-datasource,
        grafana-athena-datasource,
        grafana-atlassianstatuspage-datasource,
        grafana-aurora-datasource,
        grafana-azure-data-explorer-datasource,
        grafana-azure-monitor-datasource,
        grafana-azurecosmosdb-datasource,
        grafana-azuredevops-datasource,
        grafana-azureprometheus-datasource,
        grafana-bigquery-datasource,
        grafana-catchpoint-datasource,
        grafana-clickhouse-datasource,
        grafana-cloudflare-datasource,
        grafana-cockroachdb-datasource,
        grafana-databricks-datasource,
        grafana-datadog-datasource,
        grafana-drone-datasource,
        grafana-dynamodb-datasource,
        grafana-dynatrace-datasource,
        grafana-falconlogscale-datasource,
        grafana-github-datasource,
        grafana-gitlab-datasource,
        grafana-googlesheets-datasource,
        grafana-hello-datasource,
        grafana-helloworld-datasource,
        grafana-honeycomb-datasource,
        grafana-iot-sitewise-datasource,
        grafana-iot-twinmaker-app,
        grafana-jenkins-datasource,
        grafana-jira-datasource,
        grafana-logicmonitor-datasource,
        grafana-looker-datasource,
        grafana-mock-datasource,
        grafana-mongodb-datasource,
        grafana-mqtt-datasource,
        grafana-netlify-datasource,
        grafana-newrelic-datasource,
        grafana-odbc-datasource,
        grafana-opensearch-datasource,
        grafana-oracle-datasource,
        grafana-pagerduty-datasource,
        grafana-pyroscope-datasource,
        grafana-redshift-datasource,
        grafana-salesforce-datasource,
        grafana-saphana-datasource,
        grafana-sentry-datasource,
        grafana-servicenow-datasource,
        grafana-snowflake-datasource,
        grafana-solarwinds-datasource,
        grafana-splunk-datasource,
        grafana-splunk-monitoring-datasource,
        grafana-sumologic-datasource,
        grafana-supabase-datasource,
        grafana-timestream-datasource,
        grafana-vercel-datasource,
        grafana-wavefront-datasource,
        grafana-x-ray-datasource,
        grafana-yugabyte-datasource,
        grafana-zendesk-datasource,
        marcusolsson-csv-datasource,
        yesoreyeram-infinity-datasource
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat >/etc/grafana/provisioning/datasources/default.yml <<'EOF'
        apiVersion: 1
        datasources:
          - name: prometheus - default
            uid: prometheus-default
            type: prometheus
          - name: loki - default
            uid: loki-default
            type: loki
          - name: tempo - default
            uid: tempo-default
            type: tempo
          - name: grafana-pyroscope-datasource - default
            uid: grafana-pyroscope-datasource-default
            type: grafana-pyroscope-datasource
          - name: cloudwatch - default
            uid: cloudwatch-default
            type: cloudwatch
          - name: dlopes7-appdynamics-datasource - default
            uid: dlopes7-appdynamics-datasource-default
            type: dlopes7-appdynamics-datasource
          - name: elasticsearch - default
            uid: elasticsearch-default
            type: elasticsearch
          - name: grafana-adobeanalytics-datasource - default
            uid: grafana-adobeanalytics-datasource-default
            type: grafana-adobeanalytics-datasource
          - name: grafana-amazonprometheus-datasource - default
            uid: grafana-amazonprometheus-datasource-default
            type: grafana-amazonprometheus-datasource
          - name: grafana-astradb-datasource - default
            uid: grafana-astradb-datasource-default
            type: grafana-astradb-datasource
          - name: grafana-athena-datasource - default
            uid: grafana-athena-datasource-default
            type: grafana-athena-datasource
          - name: grafana-atlassianstatuspage-datasource - default
            uid: grafana-atlassianstatuspage-datasource-default
            type: grafana-atlassianstatuspage-datasource
          - name: grafana-aurora-datasource - default
            uid: grafana-aurora-datasource-default
            type: grafana-aurora-datasource
          - name: grafana-azure-data-explorer-datasource - default
            uid: grafana-azure-data-explorer-datasource-default
            type: grafana-azure-data-explorer-datasource
          - name: grafana-azure-monitor-datasource - default
            uid: grafana-azure-monitor-datasource-default
            type: grafana-azure-monitor-datasource
          - name: grafana-azurecosmosdb-datasource - default
            uid: grafana-azurecosmosdb-datasource-default
            type: grafana-azurecosmosdb-datasource
          - name: grafana-azuredevops-datasource - default
            uid: grafana-azuredevops-datasource-default
            type: grafana-azuredevops-datasource
          - name: grafana-azureprometheus-datasource - default
            uid: grafana-azureprometheus-datasource-default
            type: grafana-azureprometheus-datasource
          - name: grafana-bigquery-datasource - default
            uid: grafana-bigquery-datasource-default
            type: grafana-bigquery-datasource
          - name: grafana-catchpoint-datasource - default
            uid: grafana-catchpoint-datasource-default
            type: grafana-catchpoint-datasource
          - name: grafana-clickhouse-datasource - default
            uid: grafana-clickhouse-datasource-default
            type: grafana-clickhouse-datasource
          - name: grafana-cloudflare-datasource - default
            uid: grafana-cloudflare-datasource-default
            type: grafana-cloudflare-datasource
          - name: grafana-cockroachdb-datasource - default
            uid: grafana-cockroachdb-datasource-default
            type: grafana-cockroachdb-datasource
          - name: grafana-databricks-datasource - default
            uid: grafana-databricks-datasource-default
            type: grafana-databricks-datasource
          - name: grafana-datadog-datasource - default
            uid: grafana-datadog-datasource-default
            type: grafana-datadog-datasource
          - name: grafana-drone-datasource - default
            uid: grafana-drone-datasource-default
            type: grafana-drone-datasource
          - name: grafana-dynamodb-datasource - default
            uid: grafana-dynamodb-datasource-default
            type: grafana-dynamodb-datasource
          - name: grafana-dynatrace-datasource - default
            uid: grafana-dynatrace-datasource-default
            type: grafana-dynatrace-datasource
          - name: grafana-falconlogscale-datasource - default
            uid: grafana-falconlogscale-datasource-default
            type: grafana-falconlogscale-datasource
          - name: grafana-github-datasource - default
            uid: grafana-github-datasource-default
            type: grafana-github-datasource
          - name: grafana-gitlab-datasource - default
            uid: grafana-gitlab-datasource-default
            type: grafana-gitlab-datasource
          - name: grafana-googlesheets-datasource - default
            uid: grafana-googlesheets-datasource-default
            type: grafana-googlesheets-datasource
          - name: grafana-hello-datasource - default
            uid: grafana-hello-datasource-default
            type: grafana-hello-datasource
          - name: grafana-helloworld-datasource - default
            uid: grafana-helloworld-datasource-default
            type: grafana-helloworld-datasource
          - name: grafana-honeycomb-datasource - default
            uid: grafana-honeycomb-datasource-default
            type: grafana-honeycomb-datasource
          - name: grafana-iot-sitewise-datasource - default
            uid: grafana-iot-sitewise-datasource-default
            type: grafana-iot-sitewise-datasource
          - name: grafana-iot-twinmaker-datasource - default
            uid: grafana-iot-twinmaker-datasource-default
            type: grafana-iot-twinmaker-datasource
          - name: grafana-jenkins-datasource - default
            uid: grafana-jenkins-datasource-default
            type: grafana-jenkins-datasource
          - name: grafana-jira-datasource - default
            uid: grafana-jira-datasource-default
            type: grafana-jira-datasource
          - name: grafana-logicmonitor-datasource - default
            uid: grafana-logicmonitor-datasource-default
            type: grafana-logicmonitor-datasource
          - name: grafana-looker-datasource - default
            uid: grafana-looker-datasource-default
            type: grafana-looker-datasource
          - name: grafana-mock-datasource - default
            uid: grafana-mock-datasource-default
            type: grafana-mock-datasource
          - name: grafana-mongodb-datasource - default
            uid: grafana-mongodb-datasource-default
            type: grafana-mongodb-datasource
          - name: grafana-mqtt-datasource - default
            uid: grafana-mqtt-datasource-default
            type: grafana-mqtt-datasource
          - name: grafana-netlify-datasource - default
            uid: grafana-netlify-datasource-default
            type: grafana-netlify-datasource
          - name: grafana-newrelic-datasource - default
            uid: grafana-newrelic-datasource-default
            type: grafana-newrelic-datasource
          - name: grafana-odbc-datasource - default
            uid: grafana-odbc-datasource-default
            type: grafana-odbc-datasource
          - name: grafana-opensearch-datasource - default
            uid: grafana-opensearch-datasource-default
            type: grafana-opensearch-datasource
          - name: grafana-oracle-datasource - default
            uid: grafana-oracle-datasource-default
            type: grafana-oracle-datasource
          - name: grafana-pagerduty-datasource - default
            uid: grafana-pagerduty-datasource-default
            type: grafana-pagerduty-datasource
          - name: grafana-postgresql-datasource - default
            uid: grafana-postgresql-datasource-default
            type: grafana-postgresql-datasource
          - name: grafana-redshift-datasource - default
            uid: grafana-redshift-datasource-default
            type: grafana-redshift-datasource
          - name: grafana-salesforce-datasource - default
            uid: grafana-salesforce-datasource-default
            type: grafana-salesforce-datasource
          - name: grafana-saphana-datasource - default
            uid: grafana-saphana-datasource-default
            type: grafana-saphana-datasource
          - name: grafana-sentry-datasource - default
            uid: grafana-sentry-datasource-default
            type: grafana-sentry-datasource
          - name: grafana-servicenow-datasource - default
            uid: grafana-servicenow-datasource-default
            type: grafana-servicenow-datasource
          - name: grafana-snowflake-datasource - default
            uid: grafana-snowflake-datasource-default
            type: grafana-snowflake-datasource
          - name: grafana-solarwinds-datasource - default
            uid: grafana-solarwinds-datasource-default
            type: grafana-solarwinds-datasource
          - name: grafana-splunk-datasource - default
            uid: grafana-splunk-datasource-default
            type: grafana-splunk-datasource
          - name: grafana-splunk-monitoring-datasource - default
            uid: grafana-splunk-monitoring-datasource-default
            type: grafana-splunk-monitoring-datasource
          - name: grafana-sumologic-datasource - default
            uid: grafana-sumologic-datasource-default
            type: grafana-sumologic-datasource
          - name: grafana-supabase-datasource - default
            uid: grafana-supabase-datasource-default
            type: grafana-supabase-datasource
          - name: grafana-timestream-datasource - default
            uid: grafana-timestream-datasource-default
            type: grafana-timestream-datasource
          - name: grafana-vercel-datasource - default
            uid: grafana-vercel-datasource-default
            type: grafana-vercel-datasource
          - name: grafana-wavefront-datasource - default
            uid: grafana-wavefront-datasource-default
            type: grafana-wavefront-datasource
          - name: grafana-x-ray-datasource - default
            uid: grafana-x-ray-datasource-default
            type: grafana-x-ray-datasource
          - name: grafana-yugabyte-datasource - default
            uid: grafana-yugabyte-datasource-default
            type: grafana-yugabyte-datasource
          - name: grafana-zendesk-datasource - default
            uid: grafana-zendesk-datasource-default
            type: grafana-zendesk-datasource
          - name: graphite - default
            uid: graphite-default
            type: graphite
          - name: influxdb - default
            uid: influxdb-default
            type: influxdb
          - name: jaeger - default
            uid: jaeger-default
            type: jaeger
          - name: marcusolsson-csv-datasource - default
            uid: marcusolsson-csv-datasource-default
            type: marcusolsson-csv-datasource
          - name: mssql - default
            uid: mssql-default
            type: mssql
          - name: mysql - default
            uid: mysql-default
            type: mysql
          - name: opentsdb - default
            uid: opentsdb-default
            type: opentsdb
          - name: parca - default
            uid: parca-default
            type: parca
          - name: stackdriver - default
            uid: stackdriver-default
            type: stackdriver
          - name: yesoreyeram-infinity-datasource - default
            uid: yesoreyeram-infinity-datasource-default
            type: yesoreyeram-infinity-datasource
          - name: zipkin - default
            uid: zipkin-default
            type: zipkin
          - name: grafana-testdata-datasource - default
            uid: grafana-testdata-datasource-default
            type: grafana-testdata-datasource
        EOF
        exec /run.sh
